import type { Metadata } from "next";
import "./globals.css";
import db from "@/db/drizzle";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import { ToastProvider } from "@/components/providers/toaster-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body
          className={`antialiased`}
        >
          <ToastProvider/>
          {children}
        </body>
      </html>
    </SessionProvider>
  );
}
